#!/usr/local/bin/php
<?php

require 'vendor/autoload.php';

use Acme\Account\FileBasedAccountRepository;
use Acme\Bank;
use Acme\Transfer;
use Acme\BankAccount;

$bank = new Bank();
$transfer = Transfer::amount($argv[1])
    ->from(new BankAccount(new FileBasedAccountRepository($argv[2])))
    ->to(new BankAccount(new FileBasedAccountRepository($argv[3])));

try {
    $bank->execute($transfer);
} catch (RuntimeException $e) {
    echo $e->getMessage();
}
